os: osx
sudo: false

env:
  global:
    - RELEASE_VERSION=${TRAVIS_TAG}

before_install:
  - brew update
  - brew install launch4j

script:
  - ./gradlew build --info

deploy:
  provider: script
  script: ./gradlew bintrayUpload --info
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
